// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE1_Project.Models;

namespace SE1_Project.Migrations
{
    [DbContext(typeof(SE1_ProjectContext))]
    [Migration("20190919171356_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SE1_Project.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("city");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("fName");

                    b.Property<string>("lName");

                    b.Property<string>("phoneNumber")
                        .IsRequired();

                    b.Property<string>("state");

                    b.Property<string>("streetAddress");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SE1_Project.Models.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("averageRating");

                    b.Property<string>("city");

                    b.Property<string>("company");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("fName");

                    b.Property<string>("image");

                    b.Property<string>("lName");

                    b.Property<string>("phoneNumber")
                        .IsRequired();

                    b.Property<string>("profession");

                    b.Property<decimal>("rate");

                    b.Property<string>("state");

                    b.Property<string>("streetAddress");

                    b.HasKey("Id");

                    b.ToTable("Professional");
                });

            modelBuilder.Entity("SE1_Project.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("InteractionDate");

                    b.Property<int>("ProfessionalId");

                    b.Property<int>("rating");

                    b.Property<string>("reviewText");

                    b.HasKey("ID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("SE1_Project.Models.Review", b =>
                {
                    b.HasOne("SE1_Project.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SE1_Project.Models.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
